sudo: required
services:
  - docker

before_install:
  - docker build -t akoredeagbomeji/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akoredeagbomeji/docker-react npm run test -- -- coverage

deploy:
  proviver: elasticbeamstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeamstalk-us-west-2"
  bucket_path: "docker-react"
  on:
    branch: main